feat: make jitter interval configurable
cloudfoundry/route-emitter pull request #31
Opened 2024-01-04 19:55 UTC by raghunathd8

Making jitter interval configurable. Added new config parameter: `JitterFactor` which defaults to [original](https://github.com/cloudfoundry/route-emitter/blob/main/scheduler/routebroadcastscheduler.go#L98C2-L98C2) `0.2`.

2024-01-05 08:38 UTC, maxmoehl commented on scheduler/routebroadcastscheduler.go
> +	jitter_factor float64,
Please always use camelCase instead of snake_case in go.

2024-01-15 12:42 UTC, domdom82 requested changes

2024-01-15 12:42 UTC, domdom82 commented on cmd/route-emitter/main.go
> +	externalScheduler := scheduler.NewRouteBroadcastScheduler(clock, natsClient, logger, "router", cfg.JitterFactor, externalChan)
```suggestion
	externalScheduler := scheduler.NewRouteBroadcastScheduler(clock, natsClient, logger, "router", cfg, externalChan)
```

I'd prefer handing down the config and make it more flexible. If there are more properties to configure in the future, we won't have to change this again.

2024-01-15 12:42 UTC, domdom82 commented on cmd/route-emitter/main.go
> +	internalScheduler := scheduler.NewRouteBroadcastScheduler(clock, natsClient, logger, "service-discovery", cfg.JitterFactor, internalChan)
```suggestion
	internalScheduler := scheduler.NewRouteBroadcastScheduler(clock, natsClient, logger, "service-discovery", cfg, internalChan)
```

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler.go
> +	jitterFactor float64,
```suggestion
	cfg *config,
```

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler.go
> +	jitterFactor         float64
```suggestion
	cfg         *config
```

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler.go
> +		jitterFactor:         jitterFactor,
```suggestion
		cfg:         cfg,
```

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler.go
> +			jitterInterval := randSource.Int63n(int64(s.jitterFactor * float64(registerInterval)))
```suggestion
			jitterInterval := randSource.Int63n(int64(s.cfg.jitterFactor * float64(registerInterval)))
```

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler_test.go
> +		jitterFactor    float64
user a default config here instead

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler_test.go
> +				jitterFactor = 0.2
fill the value for `jitterFactor` of the default config here

2024-01-15 12:42 UTC, domdom82 commented on scheduler/routebroadcastscheduler_test.go
> +				schedulerRunner = scheduler.NewRouteBroadcastScheduler(clock, natsClient, logger, prefix, jitterFactor, emitCh)
pass down a pointer to the default config instead

2024-01-16 15:23 UTC, domdom82 requested changes

2024-01-16 15:23 UTC, domdom82 commented on scheduler/routebroadcastscheduler_test.go
> +				cfg.JitterFactor = 0.2
this won't work. you've initialized`cfg` as a pointer to config.RouteEmitterConfig in line 25 but never gave it any value to point to. so this test will throw a nil ref panic. please run your tests first before requesting a review.

I've added a suggestion that fixes the issue.
```suggestion
				cfg = &config.RouteEmitterConfig{}
				cfg.JitterFactor = 0.2
```

2024-01-18 13:47 UTC, domdom82 approved these changes

2024-01-18 16:37 UTC, ameowlia approved these changes

2024-01-18 16:37 UTC, merged